pom.xml

chore(Build): Add npm goal to build

---

src/web/app/configuration/thingConfig.tpl.html

fix(Thing): Fix dropdown of thing configuration groups

---

src/web/app/configuration/itemEdit.js

fix(Thing): Fix UI when creating new item from channel

---

Gruntfile.js
bower.json

chore(Dependancies): Update ui-select to fix dropdown list bug

---

Gruntfile.js
bower.json
src/web/app/configuration/itemEdit.js
src/web/app/dashboard/dashboard.tpl.html
src/web/app/dashboard/dashboardGaugeWidget.js
src/web/app/dashboard/dashboardWidgetProperties.tpl.html
src/web/app/models/eventModel.js
src/web/app/models/extensionModel.js
src/web/app/models/inboxModel.js
src/web/app/models/itemModel.js
src/web/app/models/thingModel.js

fix(Dashboard): Fix dashboard dropdown button

---

Gruntfile.js
bower.json
src/web/app/configuration/extensionsConfig.tpl.html
src/web/app/configuration/itemEdit.js
src/web/app/configuration/servicesConfig.js
src/web/app/configuration/servicesConfig.tpl.html
src/web/app/dashboard/dashboard.tpl.html
src/web/app/dashboard/dashboardGaugeWidget.js
src/web/app/dashboard/dashboardWidgetProperties.tpl.html
src/web/app/models/configModel.js
src/web/app/models/eventModel.js
src/web/app/models/extensionModel.js
src/web/app/models/inboxModel.js
src/web/app/models/itemModel.js
src/web/app/models/thingModel.js
src/web/app/tools/zwave/logService.js

feat(Extensions): Add version indicator in Extensions UI

---

META-INF/MANIFEST.MF
src/main/java/org/openhab/ui/habmin/internal/services/chart/ChartResource.java
src/main/java/org/openhab/ui/habmin/internal/services/dashboard/DashboardResource.java
src/main/java/org/openhab/ui/habmin/internal/services/designer/DesignerResource.java
src/main/java/org/openhab/ui/habmin/internal/services/floorplan/FloorplanResource.java
src/main/java/org/openhab/ui/habmin/internal/services/rule/RuleResource.java

feat(UI): Initial addition of REST documentation

---

src/web/app/configuration/extensionsConfig.tpl.html

feat(UI): Add links to documentation in extensions list

---

src/web/app/configuration/bindingConfig.tpl.html

feat(ZWave): Add link from binding thingTypes to database

---

src/web/app/configuration/thingConfig.tpl.html
src/web/app/tools/zwave/logService.js
src/web/less/main.less

feat(Things): Improve detailed thing status display

---

src/web/app/configuration/bindingConfig.tpl.html
src/web/app/configuration/extensionsConfig.tpl.html
src/web/app/configuration/itemConfig.tpl.html
src/web/app/configuration/servicesConfig.tpl.html
src/web/app/configuration/thingConfig.js
src/web/app/configuration/thingConfig.tpl.html
src/web/app/persistence/persistence.tpl.html
src/web/less/main.less

feat(UI): Update layout to use new list styles

---

src/web/app/configuration/itemWidget.tpl.html
src/web/app/configuration/thingConfig.js
src/web/app/dashboard/dashboardGroupWidget.tpl.html
src/web/app/dashboard/dashboardItemWidgets.js
src/web/app/models/iconModel.js
src/web/app/models/itemModel.js
src/web/app/models/smarthomeModel.js
src/web/app/sitemap/sitemapColorWidget.js
src/web/app/sitemap/sitemapSliderWidget.js
src/web/app/sitemap/sitemapSwitchWidget.js

Updated item type names as per ESH changes https://github.com/eclipse/smarthome/pull/1979.
fixes #209 

fix(UI): Update item types to remove 'item' (new ESH definition)

---

src/web/app/models/eventModel.js

feat(UI): Add binding event notifications for ZWave

---

src/web/app/models/itemModel.js

chore(Things): Fix error when updating item types

---

src/web/app/tools/zwave/logService.js

feat(ZWave): Update log viewer to better handle multi_instance encap

---

src/web/app/tools/zwave/logService.js

feat(ZWave): Update log service to add COLOR command class

---

src/web/app/home/home.tpl.html

Signed-off-by: Kai Kreuzer <kai@openhab.org>

fixed name and links

---

src/web/app/configuration/thingConfig.tpl.html
src/web/app/tools/zwave/logService.js

fix(Things): Fix thing description label in thing configuration

---

src/web/app/dashboard/dashboardGaugeProperties.tpl.html

Bugfix scaleMax was not transferred

scaleMax in dashboardGaugeProperties.tpl.html

---

src/web/app/configuration/thingConfig.js
src/web/app/configuration/thingConfig.tpl.html

Update channel configuration to use channel rather than channel type

Update channel configuration

---

pom.xml

Signed-off-by: Kai Kreuzer <kai@openhab.org>

fixed parent version reference and removed ESH p2 repo
